# Generated by Django 3.2 on 2022-08-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_aboutus', models.TextField()),
                ('why_chooseus', models.TextField()),
            ],
        ),
    ]
