# Generated by Django 3.2 on 2022-08-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0002_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='You can split with "-" for muliple value', max_length=300)),
                ('phones', models.CharField(help_text='You can split with "-" for muliple value', max_length=300)),
                ('location', models.CharField(help_text='You can split with "-" for muliple value', max_length=400)),
            ],
        ),
    ]
