# Generated by Django 3.2 on 2022-08-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0003_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='email',
            new_name='emails',
        ),
    ]
