# Generated by Django 3.2 on 2022-08-03 21:11

import Public.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0004_rename_email_contactus_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='location_image',
            field=models.ImageField(default='w', upload_to=Public.models.upload_image_gallery_site_src),
            preserve_default=False,
        ),
    ]
