# Generated by Django 3.2 on 2022-08-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='emails',
            field=models.CharField(help_text='You can split with "," for muliple value', max_length=300),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='location',
            field=models.CharField(help_text='You can split with "," for muliple value', max_length=400),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phones',
            field=models.CharField(help_text='You can split with "," for muliple value', max_length=300),
        ),
    ]
