# Generated by Django 3.2 on 2022-08-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0007_auto_20220803_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
