# Generated by Django 3.2 on 2022-08-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0008_feedback_is_readed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
