# Generated by Django 3.2 on 2022-07-10 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0009_auto_20220710_0601'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_meals', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('time_pay', models.DateTimeField(blank=True, null=True)),
                ('price_paid', models.PositiveIntegerField(blank=True, null=True)),
                ('meals', models.ManyToManyField(to='Food.Meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
