# Generated by Django 3.2 on 2022-07-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=10.13, max_digits=8),
            preserve_default=False,
        ),
    ]
