# Generated by Django 3.2 on 2022-07-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_address_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='details_meals',
            new_name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('nothing', 'Nothing'), ('preparation', 'Preparation'), ('sending', 'Sending'), ('delivered', 'ِelivered')], default='nothing', max_length=20),
        ),
    ]
