# Generated by Django 3.2 on 2022-06-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTimeServeMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_from', models.TimeField()),
                ('end_at', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='type_of_time_serve',
        ),
        migrations.AddField(
            model_name='meal',
            name='type_of_time_serve',
            field=models.ManyToManyField(to='Food.TypeTimeServeMeal'),
        ),
    ]
