# Generated by Django 3.2 on 2022-07-20 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitmeal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifyme',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.meal'),
        ),
        migrations.AddField(
            model_name='notifyme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.category'),
        ),
        migrations.AddField(
            model_name='meal',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Food.galleryfood'),
        ),
        migrations.AddField(
            model_name='imagefood',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.galleryfood'),
        ),
        migrations.AddField(
            model_name='gallerysite',
            name='images',
            field=models.ManyToManyField(to='Food.ImageSite'),
        ),
        migrations.AddField(
            model_name='discount',
            name='meals',
            field=models.ManyToManyField(to='Food.Meal'),
        ),
        migrations.AddField(
            model_name='comment',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.meal'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealgroup',
            name='drinks',
            field=models.ManyToManyField(to='Food.Drink'),
        ),
        migrations.AddField(
            model_name='mealgroup',
            name='foods',
            field=models.ManyToManyField(to='Food.Food'),
        ),
    ]
