# Generated by Django 3.2 on 2022-07-20 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.food')),
            ],
        ),
        migrations.CreateModel(
            name='StockDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.drink')),
            ],
        ),
        migrations.AlterField(
            model_name='mealgroup',
            name='drinks',
            field=models.ManyToManyField(to='Food.StockDrink'),
        ),
        migrations.AlterField(
            model_name='mealgroup',
            name='foods',
            field=models.ManyToManyField(to='Food.StockFood'),
        ),
    ]
