# Generated by Django 3.2 on 2022-07-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_auto_20220720_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealgroup',
            name='drinks',
            field=models.ManyToManyField(blank=True, null=True, to='Food.StockDrink'),
        ),
        migrations.AlterField(
            model_name='mealgroup',
            name='foods',
            field=models.ManyToManyField(blank=True, null=True, to='Food.StockFood'),
        ),
    ]
