# Generated by Django 3.2 on 2022-07-05 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 14, 59, 2, 387903, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
