# Generated by Django 3.2 on 2022-07-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_auto_20220720_0748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GallerySite',
        ),
        migrations.DeleteModel(
            name='ImageSite',
        ),
    ]
