# Generated by Django 3.2 on 2022-07-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_discount_time_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='type_of_time_serve',
        ),
        migrations.DeleteModel(
            name='TypeTimeServeMeal',
        ),
    ]
