# Generated by Django 3.2 on 2022-07-09 16:42

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('get_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
