# Generated by Django 3.2 on 2022-07-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0008_alter_comment_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
