# Generated by Django 3.2 on 2022-07-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0012_notifyme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
